version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_CONTAINER}
    env_file: .env
    environment:
      - NODE_OPTIONS=--max-old-space-size=2048
    ports:
      - "${APP_PORT}:${APP_PORT}" # Map host:container port using APP_PORT (e.g., 3000:3000)
    depends_on:
      - db
    volumes:
      - uploads_data:/app/uploads
    restart: unless-stopped

  db:
    image: postgres:17.2
    container_name: ${DB_CONTAINER}
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  uploads_data:
